# frozen_string_literal: true

# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: %i[mswin mingw]

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: %i[mswin mingw jruby]

# Middleman Gems
gem 'middleman', '>= 4.0.0'
gem 'middleman-compass', '>= 4.0.0'
gem 'middleman-livereload'
