#!/usr/bin/env ruby
# frozen_string_literal: true

require 'songbook'
require 'songbook/generate_song_files'

input_path = Songbook.select_input_path(ARGV.first)
output_path = Songbook.select_output_path(input_path: input_path, output_path: ARGV.last)

service = Songbook::GenerateSongFiles.new(
  input_path: input_path, output_path: output_path, verbose: true
)

service.call
